name = "cms"
compatibility_date = "2024-04-26"
compatibility_flags = ["nodejs_compat"]

# account_id = "a44770b6d89c0ca3f00ef61b49135478" # â† Replace with your Account ID.
# workers_dev = f
pages_build_output_dir = "./.vercel/output/static"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name =
database_id =
migrations_dir = "./prisma/migrations" # Customize this value to rename the `migrations` folder


[[r2_buckets]]
binding = 'BUCKET' # <~ valid JavaScript variable name
bucket_name = 