name = "da-acsta-api"
compatibility_date = "2023-12-01"
compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

account_id = "b068d51adac82f13a69a676e90a559a3" # â† Replace with your Account ID.
workers_dev = true

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "da-acsta-db"
database_id = "cb4e05a4-4daf-4850-ae88-cf78c6117465"


[[r2_buckets]]
binding = 'BUCKET' # <~ valid JavaScript variable name
bucket_name = 'da-acsta-bucket'