name = "api"
compatibility_date = "2023-12-01"

# [vars]
# MY_VAR = "my-variable"

account_id = "a44770b6d89c0ca3f00ef61b49135478" # â† Replace with your Account ID.
workers_dev = true

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "da-acsta-db"
database_id = "010bc5b5-c591-4ef7-ac09-00ccf739c274"



[[r2_buckets]]
binding = 'BUCKET' # <~ valid JavaScript variable name
bucket_name = 'da-acsta'